### ISSUE TITLE
Add Steam provider

### ISSUE THREAD

**Issue by Akira-Webster** [aspnet-contrib/AspNet.Security.OpenId.Providers#1]
Because the asp.net team has implemented their UseOpenIdConnectAuthentication() middleware to use only OAuth2 and OpenID Connect (based on OAuth2) which means it is not compatible with providers like STEAM that use OpenID 2.0.

There seems to be some other interest in this as well. REF: http://stackoverflow.com/questions/31101803/implementing-openid-in-asp5

I believe this makes more sense to support in a community project like this instead of main repo. REF: https://github.com/aspnet/Security/

**Comment by PinpointTownes** [comment]
Thanks for the suggestion!

OAuth2 providers are definitely our main priority, but I'll make sure to upload a working OpenID 2.0 base handler as soon as possible. Implementing specific providers like Steam should be far easier with a common design.

/cc @jerriep

**Comment by PinpointTownes** [comment]
FYI, I almost finished the first prototype of the OpenID 2.0 base handler and it works fine with Steam.

I'll probably send a PR tomorrow and ask @jerriep to take a look :smile:

**Comment by jerriep** [comment]
Cool :) I'll be travelling quite a bit though for the next 4 days, but should be able to fit in something inbetween

**Comment by PinpointTownes** [comment]
@Akira-Webster the Steam provider is done, but I'd like to test it. Could you please create an API key and share it?
You can join https://gitter.im/aspnet-contrib/AspNet.Security.OpenId.Providers and send it via PM if you prefer.

**Comment by Akira-Webster** [comment]
@PinpointTownes below is one of my development keys it will be revoked in 10 days. Please let me know if you need longer then that.

D929B1E7DFCC5FABB23DE7969F813E5E

**Comment by PinpointTownes** [comment]
Thank you, that was really helpful :smile: 

If you're interested in using the early bits of the Steam provider, you can take a look at this sample: https://github.com/PinpointTownes/AspNet.Security.OpenId.Providers/tree/sample

Don't hesitate to brutalize it but please don't use it for a production app :smile: 
Feel free to share your remarks and criticisms.
