### ISSUE TITLE
[Question] How to get the user's Steam ID

### ISSUE THREAD

**Issue by Hona** [aspnet-contrib/AspNet.Security.OpenId.Providers#107]
Is this available as a claim?

**Comment by Hona** [comment]
It probably should be noted that I want to port this code to C# https://github.com/momentum-mod/website/blob/staging/server/config/express.js#L93-L121

It essentially checks if the Steam user has setup a profile, and that is is a premium account.

**Comment by kinosang** [comment]
use `ClaimTypes.NameIdentifier`, it's a URL which contains Steam ID (64).

**Comment by kevinchalet** [comment]
@Hona when nice people take some time to help you, you could at least thank them... no? 😕
