### ISSUE TITLE
[Question] How to get the user profile object after authentication

### ISSUE THREAD

**Issue by Hona** [aspnet-contrib/AspNet.Security.OpenId.Providers#108]

**Comment by martincostello** [comment]
Use the `OnAuthenticated` event. 

https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/49d4cb73d5c6c0901b55ab9f7df7b74e8241823f/src/AspNet.Security.OpenId/OpenIdAuthenticationEvents.cs#L23
