### ISSUE TITLE
Is there any way I can login to asp.net using an API using a steam token

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [aspnet-contrib/AspNet.Security.OpenId.Providers#138]
### Provider name
Steam
_State which provider(s) you are experiencing an issue with._
no issues but a  question

I want to login to my asp.net app using the steam user token i get from the steam client in my game
Is there any way I an write an api to do that instead of going with the web based flow?

**Comment by kevinchalet** [comment]
https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/ should put you on the right track.
