### ISSUE TITLE
'HttpContext' does not contain a definition for 'GetExternalProvidersAsync' or for 'IsProviderSupportedAsync'

### ISSUE THREAD

**Issue by ggelu** [aspnet-contrib/AspNet.Security.OpenId.Providers#144]
I am making a web app with Steam login and I tried using the sample code but I can't use the 2 functions mentioned in the title.
Am I missing a package or something?

I added:

       builder.Services.AddAuthentication().AddSteam();
       app.UseAuthorization();
       app.UseAuthentication();

in the Program.cs.

**Comment by kevinchalet** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/e89b0978c49852bd237c0aaf71d1797de048e873/samples/Mvc.Client/Extensions/HttpContextExtensions.cs#L11-L29
