### ISSUE TITLE
ASP.NET Identity

### ISSUE THREAD

**Issue by j2ghz** [aspnet-contrib/AspNet.Security.OpenId.Providers#26]
I have a similar problem as #25. I created a new project `.NET Core` > `ASP.NET Core Web Application (.NET Core)` > `Web Application (Change Authentication > Individual User Accounts)`, I added this nuget package and added a line to Startup.cs:
```
            app.UseIdentity();
            
            // Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715
            app.UseSteamAuthentication();

            app.UseMvc(
                routes => { routes.MapRoute(name: "default", template: "{controller=Home}/{action=Index}/{id?}"); });
        }
```
But I get just one claim from steam and that is
```
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod: Steam
```

**Comment by j2ghz** [comment]
I tried https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/issues/25#issuecomment-250963404, now I get user name as well, but still no steam id

It appears to be a problem with ASP.NET Identity
These are all the claims I can access in User object in Controllers and Views:
```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: ebcadd2b-5385-41bd-9a78-cf455184b1f1
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: J2ghz
AspNet.Identity.SecurityStamp: 1980c36c-4db2-4616-975f-f06594dd4de0
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod: Steam
```
When receiving the callback from Steam when authenticating, using `signInManager.GetExternalLoginInfoAsync()` I get these:
```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: http://steamcommunity.com/openid/id/01234567890123456
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: J2ghz
```
I guess they are stored, because I can access the user name, but since the type `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier` is the same for steam id as well as internal user id in database it gets overwritten.

**Comment by PinpointTownes** [comment]
That's expected because ASP.NET Core Identity doesn't persist the external provider claims (it's something you must do yourself)

You can read https://github.com/aspnet/Identity/issues/628 for more information.

**Comment by StummeJ** [comment]
aspnet/Identity#628 is exactly the problem!
