### ISSUE TITLE
Getting Steam User Data

### ISSUE THREAD

**Issue by bkonzUNOmaha** [aspnet-contrib/AspNet.Security.OpenId.Providers#28]
I made a demo .net core framework application using this and intigrated it with the code provided in the sample in this repo. I got as far as bringing up the steam page for loggining in, but when the login in a success and the site redirects the user, I have no way to view the user data. The sample code uses `@if (User?.Identity?.IsAuthenticated ?? false)`, but when I try that the code always goes to the else block.

Github Repo: https://github.com/bkonzUNOmaha/SteamOpenIDTest/tree/master/Steamtest2/src/Steamtest2

**Comment by bkonzUNOmaha** [comment]
So I figured out that problems were happening when I was using steam authentication with identity. Once I removed the identity calls from `startup.cs`, everything worked. Is there a way to use steam authentication along with Identity?

**Comment by PinpointTownes** [comment]
The Steam provider works exactly like any other authentication middleware, so I'd recommend having a look at the Identity samples/templates that use external authentication to see how you're supposed to integrate things.

**Comment by bkonzUNOmaha** [comment]
So I made a new project and added some of the started code in the sample so that Steam shows up as another service to log in, however I seem to be having the same problem as issue as #26, where my claims show that the user is associated with steam, but I cannot get any information other than `http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod: Steam`. Since I am using ASP .net core framework, it doesn't seem like I have the `GetExternalLoginInfoAsync()` method. What would be an alternative for this method?

**Comment by kevinchalet** [comment]
`GetExternalLoginInfoAsync()` is defined here: https://github.com/aspnet/Identity/blob/1.0.0/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L438.
