### ISSUE TITLE
Port the social providers to the new ASP.NET Core 2.0 authentication stack

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OpenId.Providers#34]

**Comment by mrphil2105** [comment]
Yes please update it, that would be awesome. I can't really get my asp.net core 2.0 website any further without this.

**Comment by kevinchalet** [comment]
@mrphil2105 I currently don't have the bandwidth needed to make that happen. Would you be interested in contributing or funding the work?

**Comment by mrphil2105** [comment]
Hmm, I would love to contribute, but Asp.Net Core is still fairly new to me, so I don't know much of the authentication stuff. Though I do code C# fluently.

**Comment by kevinchalet** [comment]
Done thanks to @kinosang! :clap: 

Packages are being created at this moment and will be available on our MyGet nightly builds feed.

**Comment by mrphil2105** [comment]
Thanks a ton @kinosang

**Comment by shravan2x** [comment]
@PinpointTownes Any update on when the NuGet packages will be out?

**Comment by kinosang** [comment]
@shravan2x packages already published on myget.

**Comment by shravan2x** [comment]
@kinosang Are there any plans of pushing to nuget?

**Comment by shravan2x** [comment]
@kinosang I see. Any idea when the official release date of 2.0 on nuget is?

**Comment by kinosang** [comment]
@shravan2x I don't know, @PinpointTownes may have roadmap for that.

**Comment by kevinchalet** [comment]
The OpenID2 and OAuth2 providers for 1.0 and 2.0 have been pushed to NuGet.org.
