### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by shravan2x** [aspnet-contrib/AspNet.Security.OpenId.Providers#36]
The current update with support for the updates for ASP.NET Core 2.0 is not live on NuGet. Could this be published?

**Comment by kevinchalet** [comment]
> Could this be published?

Not before all the OAuth2 providers are ported to 2.0. You can track the progress here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/170.

**Comment by shravan2x** [comment]
Okay, thanks for letting me know. I'll close this issue and subscribe to the other one.
