### ISSUE TITLE
Users are signed out when website is restarted

### ISSUE THREAD

**Issue by proviste** [aspnet-contrib/AspNet.Security.OpenId.Providers#41]
Steam authentication,
.net core 2 
asp.net core 2

The users stay authenticated as long as the site is not restarted. When the website is restarted, the users have to sign in again.

The sample project exhibits the same behavior

**Comment by kevinchalet** [comment]
Read https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?tabs=aspnetcore2x#data-protection.
