### ISSUE TITLE
Has steam has changes the return data?

### ISSUE THREAD

**Issue by Zexuz** [aspnet-contrib/AspNet.Security.OpenId.Providers#43]
AspNet.Security.OpenId.Steam.SteamAuthenticationHandler[0]
      The userinfo request was skipped because an invalid identifier was received: https://steamcommunity.com/openid/id/<steamid>.

It was **http**://steamcommu... before.

I think the problem lies here. https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/a1936973ad02b37b233eb900ae4fbc65d814993f/src/AspNet.Security.OpenId.Steam/SteamAuthenticationHandler.cs#L60

**Comment by proviste** [comment]
Merci
