### ISSUE TITLE
OpenId.Steam fails to load user data

### ISSUE THREAD

**Issue by dillonwd6086** [aspnet-contrib/AspNet.Security.OpenId.Providers#47]
I have added the service like 
`              .AddSteam(options =>
                {
                    options.UserInformationEndpoint = SteamAuthenticationDefaults.UserInformationEndpoint;
                    options.ApplicationKey = "*Correct Key*";
                });
`
It works correctly and creates a valid cookie, however when trying to load the data from the steam api I receive the following error
`warn: AspNet.Security.OpenId.Steam.SteamAuthenticationHandler[0]
      The userinfo request was skipped because an invalid identifier was received: https://steamcommunity.com/openid/id/76561198832475883.`

**Comment by dillonwd6086** [comment]
Using the decompiler, it seems that the version on Nuget is not as up to-date and does not support https

**Comment by kinosang** [comment]
@dillonwd6086 use the MyGet repository

**Comment by kevinchalet** [comment]
Yep, it's been fixed in the nightly builds. RTM should ship this or next week.

**Comment by kevinchalet** [comment]
https://twitter.com/PinpointTownes/status/1008812623884967936
