### ISSUE TITLE
Don't set auth cookie on failed sign-in

### ISSUE THREAD

**Issue by shravan2x** [aspnet-contrib/AspNet.Security.OpenId.Providers#48]
This issue can be tagged as a `question`.

Following my issues with failed userinfo requests (from #46), I decided to add a handler for `OnTicketReceived` and make the userinfo request myself. In this handler, I make the userinfo request with multiple API keys and authenticate the user when one of them succeed. I would also like to handle the case where none of the API keys work (however unlikely it may be) by not authenticating the user at all. I tried using `context.Fail("some reason")`, but this still seems to set the `auth` cookie on the client machine.

Do you know any way to completely fail the authentication process? Could you also tell me what the `Success` and `Fail` methods on `TicketReceivedContext` do?

**Comment by kevinchalet** [comment]
It's definitely something that would be worth adding. Would you be interested in sending a PR to fix that?

**Comment by shravan2x** [comment]
@kevinchalet That would be difficult for me to do. The project I made this issue for was shut down late last year. As such I've lost most context around it and/or a way to test. I'm also fairly busy with my newer projects.
