### ISSUE TITLE
Steam OpenID & JWTs

### ISSUE THREAD

**Issue by jacobmstein** [aspnet-contrib/AspNet.Security.OpenId.Providers#50]
When using the default JWT middleware instead of cookies I get `An unhandled exception occurred while processing the request. The authentication handler registered for scheme 'Bearer' is 'JwtBearerHandler' which cannot be used for SignInAsync.`

From `ConfigureServices`:
```cs
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateAudience = true,
            ValidateIssuer = true,
            ValidateIssuerSigningKey = true,
            ValidateLifetime = true,
            ValidAudience = Configuration["Jwt:Issuer"],
            ValidIssuer = Configuration["Jwt:Issuer"],
            IssuerSigningKey = new 
            SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Jwt:Key"]))
         };
     })
     .AddSteam(options =>
     {
         options.CallbackPath = "/verify";
     });
```

Is there any way to override the `/verify` callback, manually call the library to authenticate the user, then issue a JWT afterwards? My understanding is `SignInAsync` is being called automatically.

**TL;DR: Can I override the verification callback and incorporate it into my own logic, e.g. verify the user and return a value?**

Thanks,
Jacob

**Comment by volvoplz** [comment]
Did you find a way to resolve this issue ?

**Comment by jacobmstein** [comment]
Unfortunately not, I ended up switching to Node for better control over the call back.

**Comment by kevinchalet** [comment]
The JWT middleware can't be used for issuing JWT tokens: its only mission is to validate them, which is why you get an exception when trying to use it as the `DefaultSignInScheme`.

The scenario you describe is usually achieved by adding an OpenID Connect server (OIDC):

```
Client (e.g a SPA or a mobile app) -> your OIDC server embedded in your ASP.NET Core app -> Steam (OpenID 2.0 dance) -> your OIDC server -> client.
```

Projects like IdentityServer (developed by Thinktecture) or OpenIddict (that I develop and maintain) can help you with that.

**Comment by volvoplz** [comment]
Thanks a lot @PinpointTownes

That sounds exactly like what I need but I don't really understand.

If I'm hosting an IdentityServer, I'm the one who authenticates my users. Will they still be able to log into my website with their steam accounts ? And I will be able to identify their steam info ?

**Comment by kinosang** [comment]
@vlapoec IdentityServer or other OpenID Connect servers (ASOS, OpenIddict, and etc) are works well with 3rd party login, such as  OAuth and OpenID.

Please refer to Asp.Net Core Identity docs and IdentityServer docs for more information.

Simply you can just add `services.AddAuthentication().AddSteam()` and `app.UseAuthentication()` (for IdentityServer it's replaced by `app.UseIdentityServer()`)

**Comment by volvoplz** [comment]
Thank you I will dig into that

**Comment by verdie-g** [comment]
@vlapoec I'm facing the same problem. Did you manage to solve it with IdentityServer ?

**Comment by proviste** [comment]
@verdie-g 
I'm sorry. I did it very differently...

**Comment by verdie-g** [comment]
I have found another solution which is handling the redirection yourself in SteamAuthenticationOptions.Events.OnTicketReceived and passing the jwt in a query parameter. See https://stackoverflow.com/questions/59734317/return-a-jwt-after-authenticating-via-open-id.

**Comment by kevinchalet** [comment]
@verdie-g looks like a super **dangerous solution**: your `RedirectUri` endpoint accepts a `token` parameter in the query string without any additional anti-forgery validation.

The lack of CSRF countermeasures in a callback endpoint typically results in a session fixation vulnerability: nothing prevents a bad guy from authenticating with his own account, extracting the JWT associated to his account and forging a URL he'll be able to send to a victim, that will be logged in as the attacker once clicking on the link.

There's really a reason if we suggest opting for battle-tested options: these threats are clearly identified in standard protocols.

**Comment by verdie-g** [comment]
Indeed, in my case I'm forbidding CORS which I think, mitigates this security issue (?). Anyway, I should dig more into OIDC servers but it feels so overkill for the size of my project.

**Comment by kevinchalet** [comment]
> Indeed, in my case I'm forbidding CORS which I think, mitigates this security issue (?).

Nope, neither the same-origin policy nor same-site cookies will mitigate that, as the victim directly visits the vulnerable callback endpoint in the attack I described.

**Comment by verdie-g** [comment]
I misread your scenario. In my case, you have nothing to gain by allowing someone else to log in your account. But my solution is really dirty anyway.

**Comment by kevinchalet** [comment]
> In my case, you have nothing to gain by allowing someone else to log in your account.

Information theft is the main risk with this attack: if your website allows the user to send personal data, you're at risk, as the data will be attached to the attacker's account.

**Comment by verdie-g** [comment]
I understand. Thanks for pointing this issue.

**Comment by kevinchalet** [comment]
To be honest, it's not the first time I hear someone trying to implement a custom protocol instead of using a battle-tested standard like OIDC (and well-known implementations like IdSrv or OpenIddict).

I'm considering writing a blog post introducing OpenIddict 3.0's degraded mode, which allows using OpenIddict's server without any database. It's a perfect use case for a tiny proxy between a single client and a remote identity provider (Steam in this case). Would you be interested?

**Comment by verdie-g** [comment]
I would be very interested! I have started reading OpenIddict doc which is way more clearer than IdentityServer's one, no magic everywhere. But if I have implemented my custom protocol it is mostly by pure laziness because I didn't find the article matching my use case.

**Comment by volvoplz** [comment]
Well I would be interested too

**Comment by kevinchalet** [comment]
@verdie-g @vlapoec here we go: https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/ 😄

**Comment by verdie-g** [comment]
That was fast thanks! I'll read that as soon as a I can.

**Comment by kevinchalet** [comment]
@verdie-g my pleasure 😄

**Comment by kevinchalet** [comment]
Closing, as I believe my blog post answered the original question. If not, please add a comment and I'll give it a look.

**Comment by Gameghostify** [comment]
The [Cookie authentication scheme](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1) here works without having to add something as heavy as asp net core identity or even identity server to your project

On that note: Does that mean we could create a custom auth scheme that implements `SignInAsync`?

**Comment by Gameghostify** [comment]
I'd love to use steam authentication but keep using my own user system, without having to switch to one given by ASP.NET Core Identity/IdentityServer or implementing something like OpenIddict

**Comment by kevinchalet** [comment]
@Gameghostify nothing prevents you from doing that. As you figured out, you can use the cookies authentication handler alone and build your own membership mechanism on top of that.

**Comment by Gameghostify** [comment]
Thanks a lot! This seems like a very lightweight alternative (next to
OpenIddict)

Kévin Chalet <notifications@github.com> schrieb am Fr., 28. Feb. 2020,
16:38:

**Comment by vshlmahalingam** [comment]
@kevinchalet  Need to Use E2E encryption in Openiddict 3.0 instead of using a default Password hashing....Is there is a way to do it?

**Comment by jacobmstein** [comment]
> https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/

I ended up revisiting this a while later, and I really appreciate the blog post. Thank you!

I would like to just allow users to login using a SPA, and if authenticated properly, store the info in a databse, and redirect back to my SPA and display a success message. That's it, in which case I don't need to use JWTs. In that case would it be safe to override `OnTicketReceived`, as long as I ensure the `RedirectUri` is not foreign? Using a connect server seems overkill if I don't need to issue JWTs.
