### ISSUE TITLE
OnAuthenticated event not firing - Can't set Identity

### ISSUE THREAD

**Issue by KristianSv** [aspnet-contrib/AspNet.Security.OpenId.Providers#51]
There is an issue when setting Identity.
![image](https://user-images.githubusercontent.com/25365788/49812362-8fbf4000-fd65-11e8-99d1-da55cdf68bbe.png)
A breakpoint in the OnAuthenticated method is never hit, so I really can't set the Identity.
Authentication happens just fine, and CallbackPath is showed right after, as supposed.
I noticed you @kelvinmac has the same issue. Don't know if your breakpoints are hit though.
Any suggestions?
Or just any suggestion for getting Steam ID?
I'm kinda stuck because I can't retrieve any user data.

Thanks.

**Comment by lwansbrough** [comment]
This issue can happen for a number of reasons, but one potential reason could be that your application key is null.
