### ISSUE TITLE
Question: Force Request.Schema under Docker or Azure Web App (Linux)

### ISSUE THREAD

**Issue by nelfer** [aspnet-contrib/AspNet.Security.OpenId.Providers#52]
Hi,

I'm having an issue when I deploy an app to Azure Web App (Linux). These apps run under a Docker container. To the app, the request arrives with "http" schema. This causes a problem because when open id regenerates the redirect URL, it uses "http" instead of "https".

Do you know of a way to tell the app to use a different schema? Not the one in Request? Or to force Request.Schema to be "https"?

Alternatively (but very unlikely), is there a chance that you offer a setting to set the full URL for the call back (instead of just the path)?

Thanks

**Comment by kevinchalet** [comment]
Hey,

Sorry for not replying earlier, looks like your message went off the radar.
I suspect you eventually found a solution, but just in case, https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1 should put you on the right track.

Cheers.
