### ISSUE TITLE
ASP.NET Core 3.0.0 release

### ISSUE THREAD

**Issue by martincostello** [aspnet-contrib/AspNet.Security.OpenId.Providers#65]
I've merged #53 to dev and created a new [`rel/3.0.0`](https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/tree/rel/3.0.0) branch for it.

However I'm on vacation for the next two weeks so, unless it waits until after then, I won't be able to help out with pushing the final 3.0.0 release to NuGet.org.

/cc @PinpointTownes @poke

**Comment by martincostello** [comment]
~`3.0.0` packages are here: https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-openid-providers/builds/27887251/artifacts~

And here's the version metadata from .NET Reflector:

![image](https://user-images.githubusercontent.com/1439341/66224476-d3f14780-e6cd-11e9-8091-8ad77c20431c.png)

And then just putting this here now and reviewing the comment, I've realised that the `[AssemblyCompany]` is wrong. I'll dig through the code now and work out how to get that fixed, and apply it to the branch and rebuild.

**Comment by kevinchalet** [comment]
On a related note, all our packages are also incorrectly flagged as serviceable (they can't, since basically only Microsoft can service NuGet packages via Windows Update).

We'll need to fix that too.

**Comment by martincostello** [comment]
Good spot - I'll look into sorting that now too. Once things look good on this, I'll port the various fixes over to OAuth as well as back to `dev`.

**Comment by martincostello** [comment]
Updated candidate `3.0.0` packages here: https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-openid-providers/builds/27887701/artifacts

![image](https://user-images.githubusercontent.com/1439341/66225567-a1951980-e6d0-11e9-955a-69093593fcb6.png)

![image](https://user-images.githubusercontent.com/1439341/66225610-bbcef780-e6d0-11e9-90a4-8d07134d9b29.png)

**Comment by martincostello** [comment]
Release and release notes ready in GitHub too.

**Comment by kevinchalet** [comment]
The 3.0.0 packages are now on NuGet.org 🎉
