### ISSUE TITLE
Inability to send custom extensions when issuing a challenge.

### ISSUE THREAD

**Issue by joskraps** [aspnet-contrib/AspNet.Security.OpenId.Providers#72]
**Describe the bug**
We are unable to send custom extension values when a challenge is issued. We send the client id which is supplied when the user submits the login form via a query parameter.Dotnetopenauth was able to convert to our custom extension and send to the provider.

**Steps To reproduce**

- Add openId configuration to startup, specifying the custom extension: `                options.Attributes.Add("openid.ns.alias1", "http://customExtensionDomain/ext/openid/client_id/1.0");
`
- In the controller, add the parameter to authentication properties object: `            ap.SetParameter("alias1.client_id", loginModel.ClientId);
`
- Inspecting the request, the client id is not sent as expected. Additionally, adding the attribute int he configuration adds an extra openid.ax prefix to the customer extension being added.

**Expected behaviour**
I would expect to be able to add the client id that was sent to the challenge request via adding it to the authentication properties object.

**Actual behaviour**
The openId provider does not look at the properties.Parameters dictionary when a challenge has been issued and does not add any values to the request.

**System information:**
 - OS:Windows 10
 - Library Version 3.1.1
 - .NET version 3.1

**Comment by kevinchalet** [comment]
You work for Cerner? I must confess this name doesn't bring back good memories.

A few years ago, I had the opportunity to work as a contractor for a medical company, and part of my mission was to integrate with your FHIR and SMART-based APIs. You have no idea how **painful** getting even the most basic details from your marketing department - or whatever it's called - was...

I'm really tempted to offer your company the same treatment, but that would be mean, right?
