### ISSUE TITLE
Some dependencies are too old

### ISSUE THREAD

**Issue by kinosang** [aspnet-contrib/AspNet.Security.OpenId.Providers#74]
Some of the dependencies are too old, such as AngleSharp and Microsoft.IdentityModel.Protocols.

**Comment by martincostello** [comment]
Some of the dependencies are intentionally been left to be “old” to increase compatibility, as consumers are able to upgrade them themselves.

The test-related ones can be kept up-to-date, with one exception which has a comment in the code as it breaks the Apple provider.
