### ISSUE TITLE
Steam Auth Connection With React?

### ISSUE THREAD

**Issue by halitkalayci** [aspnet-contrib/AspNet.Security.OpenId.Providers#80]
**Describe the bug**
I saw something about steam&jwt are not safe together. But I wanna do a react app with a asp.net core backend but I dont know how can i authorize myself in react to access my api without jwt using cookies.

**Comment by kevinchalet** [comment]
See https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/issues/50#issuecomment-587524497.

**Comment by halitkalayci** [comment]
Great work dude!

I have one question tho, Is the output code is raw jwt or not? I can not decode it. If I want to how can i decode that?

**Comment by kevinchalet** [comment]
OpenIddict 3.0 issues encrypted JWT access tokens by default. To disable encryption, you can call `options.DisableAccessTokenEncryption()` in the server options.
