### ISSUE TITLE
Anti-forgery Token Invalid Solution - Chrome 84 

### ISSUE THREAD

**Issue by arran-nz** [aspnet-contrib/AspNet.Security.OpenId.Providers#95]
In newer versions of Chrome when authenticating with Steam, the correlation cookie is not sent back.

The correlation cookie must be set to `Secure` for `SameSite:Lax` for it to be returned.

This can be achieved by the adding the following in `Startup.cs`:
```diff
.AddSteam(options =>
                    {
+                      options.CorrelationCookie.SameSite = SameSiteMode.None;
+                      options.CorrelationCookie.SecurePolicy = CookieSecurePolicy.Always;
                    }
```

Is there any possibly to set `Secure` to `Always` by default?

**Comment by arran-nz** [comment]
Chrome changes: https://venturebeat.com/2020/07/14/google-chrome-84/

**Comment by martincostello** [comment]
These properties come via our derived classes and dependency on ASP.NET Core itself, which _should_ correctly configure cookies for Same Site provided that you are using a new enough version of ASP.NET Core: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

What version of the package are you using? What version of ASP.NET Core are you using?

As of ASP.NET Core 3.1.7 the defaults appear to be `SameSiteMode.None` and `CookieSecurePolicy.SameAsRequest`.

https://github.com/dotnet/aspnetcore/blob/1bf292d47ac2a0ebda07d8a3f00355dd01915ad5/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L29-L30

https://github.com/dotnet/aspnetcore/blob/1bf292d47ac2a0ebda07d8a3f00355dd01915ad5/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L72-L73

**Comment by arran-nz** [comment]
Thank you for the info and clarification. Will be updating ASP.NET Core.

**Comment by mrcameron999** [comment]
Thank you this was supper useful.
